### ISSUE TITLE
Grabbed tracks should add to the bottom of playlists

### ISSUE THREAD

**Issue by ImGrumpy** [musiqpad/mqp-server#41] opened 2016-04-21 14:22 UTC
When adding a song from search results to a playlist, it is appropriate for songs to be added to the top of that playlist.  However when grabbing a currently playing track, those should be added to the bottom of the playlist since they've obviously just been played.

**Comment by foodbandlt** [comment] 2016-04-21 15:10
I believe it already does that: http://i.imgur.com/ulbwNxK.png

**Comment by DerpgonCz** [comment] 2016-04-21 15:13
As @foodbandlt said, I think it is already implemented - and I have the feeling I was implementing it :eyes:

**Comment by ImGrumpy** [comment] 2016-04-21 15:52
Ok, I figured this out - it DOES add to the bottom as you show if you add it to the active playlist.  If you add it to a specific playlist, it adds it to the top instead.

**Comment by foodbandlt** [comment] 2016-04-21 16:00
Ahh, yeah.  I remember that.  I blame @DerpgonCz <3

**Comment by TheBanHammer** [comment] 2016-04-21 22:14
Closing issue as expected functionality is working. Not a Bug

**Comment by ImGrumpy** [comment] 2016-04-27 12:55
I _really_ wish you guys would reconsider this.  I can't understand the logic of adding a grabbed track to the top of any playlist since it's been recently played.  And since it adds to the _bottom_ of the playlist that's active or to the _top_ of other playlists, it's confusingly inconsistent.

**Comment by foodbandlt** [comment] 2016-04-27 13:06
Eh, I don't see why not.  I think you're right, it would make it more consistent rather than adding confusing conditions where sometimes something happens and not other times.

**Comment by TheBanHammer** [comment] 2016-05-13 15:01
Fixed in 781dfaf

**Closed as completed by TheBanHammer** 2016-05-13 15:01 UTC
Labels: Enhancement

**Comment by ImGrumpy** [comment] 2016-05-13 16:18
Ok, I hate to keep adding to this, especially if this new behavior is because I asked for it...  but I was expecting that grabbed tracks (regardless of their target playlist) would go to the bottom while searched for tracks would add to the top like they did previously.  It looks like searched for additions are also going to the bottom now?

**Comment by ImGrumpy** [comment] 2016-06-27 16:32
These fixes were somehow lost and the behavior reverted to songs always being added to the top of the playlist.  Expected behavior, add to the top for searched songs, add to the bottom for grabbed songs.
